platform: x64
configuration: Release
image: Visual Studio 2017

build_script:
 - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
 - cmake -P ci-build.cmake
 - cmake --build . --config RelWithDebInfo --target INSTALL
cache:
#- ogredeps -> CMake/Dependencies.cmake
branches:
  only:
    - seanyen_working
artifacts:
  - path: sdk
    name: ogre-sdk-master-vc15-x64
