platform: x64
configuration: Release
image: Visual Studio 2017

build_script:
 - cmake -P ci-build.cmake
 - cmake --build build --config RelWithDebInfo --target INSTALL
cache:
- ogredeps -> CMake/Dependencies.cmake
branches:
  only:
    - seanyen_working
artifacts:
  - path: build/sdk
    name: ogre-sdk-master-vc15-x64
